---
version: 2
sources:
- name: "westpac_edw_views"
  database: "westpac"
  schema: "edw_views"
  tables:
  - name: "zsgd_acct"
    config:
      tags:
      - "pipeline:zsgd_base"
      - "pipeline:manual_test"
    columns:
    - name: "Acct_Key"
      dataType:
        type: "Bigint"
    - name: "Armt_Key"
      dataType:
        type: "Bigint"
    - name: "Src_Sys_Code"
      dataType:
        type: "String"
    - name: "OD_Type"
      dataType:
        type: "String"
    - name: "From_Date"
      dataType:
        type: "Date"
    - name: "To_Date"
      dataType:
        type: "Date"
    type: "table"
  - name: "zsgd_acct_loan"
    config:
      tags:
      - "pipeline:zsgd_base"
      - "pipeline:manual_test"
    columns:
    - name: "Acct_Key"
      dataType:
        type: "Bigint"
    - name: "Repay_Type_Code"
      dataType:
        type: "String"
    - name: "From_Date"
      dataType:
        type: "Date"
    - name: "To_Date"
      dataType:
        type: "Date"
    type: "table"
  - name: "zrms_loan_account"
    config:
      tags:
      - "pipeline:rms_base"
      - "pipeline:manual_test"
    columns:
    - name: "Account_Id"
      dataType:
        type: "Bigint"
    - name: "Repayment_Type"
      dataType:
        type: "String"
    - name: "From_Date"
      dataType:
        type: "Date"
    - name: "To_Date"
      dataType:
        type: "Date"
    type: "table"
  - name: "zrms_account"
    config:
      tags:
      - "pipeline:rms_base"
      - "pipeline:manual_test"
    columns:
    - name: "Account_Id"
      dataType:
        type: "Bigint"
    - name: "Repayment_Type"
      dataType:
        type: "String"
    - name: "From_Date"
      dataType:
        type: "Date"
    - name: "To_Date"
      dataType:
        type: "Date"
    type: "table"
  - name: "zwgd_all_acct_m_hist"
    config:
      tags:
      - "pipeline:mu001_base"
    columns:
    - name: "Account_Id"
      dataType:
        type: "Bigint"
    - name: "Armt_Key"
      dataType:
        type: "Bigint"
    - name: "Source_System_Code"
      dataType:
        type: "String"
    - name: "From_Date"
      dataType:
        type: "Date"
    - name: "To_Date"
      dataType:
        type: "Date"
    type: "table"
  - name: "zwgd_mrtg_loan_m_hist"
    description: "Historical mortgage loan product information used for tracking product\
      \ types and account associations over time."
    config:
      tags:
      - "pipeline:mu001_base"
    columns:
    - name: "Account_Id"
      description: "Unique identifier for the mortgage loan account."
      dataType:
        type: "Bigint"
    - name: "Product_Code"
      description: "Code representing the specific mortgage product assigned to the\
        \ account."
      dataType:
        type: "Bigint"
    - name: "System_Product_Type"
      description: "Type of mortgage product as classified by the system."
      dataType:
        type: "String"
    - name: "From_Date"
      description: "Date when the mortgage product became active on the account."
      dataType:
        type: "Date"
    - name: "To_Date"
      description: "Date when the mortgage product was deactivated or changed on the\
        \ account."
      dataType:
        type: "Date"
    type: "table"
  - name: "ztbk_account"
    config:
      tags:
      - "pipeline:tbk_base"
      - "pipeline:manual_test"
    columns:
    - name: "Account_Id"
      dataType:
        type: "Bigint"
    - name: "Armt_Key"
      dataType:
        type: "Bigint"
    - name: "Repay_Type_Code"
      dataType:
        type: "String"
    - name: "From_Date"
      dataType:
        type: "Date"
    - name: "To_Date"
      dataType:
        type: "Date"
    type: "table"
- name: "westpac_sgdw_views"
  database: "westpac"
  schema: "sgdw_views"
  tables:
  - name: "znex_account"
    config:
      tags:
      - "pipeline:nexus_base"
    columns:
    - name: "Account_Id"
      dataType:
        type: "Bigint"
    - name: "Armt_Key"
      dataType:
        type: "Bigint"
    - name: "From_Date"
      dataType:
        type: "Date"
    - name: "To_Date"
      dataType:
        type: "Date"
    type: "table"
  - name: "znex_loan"
    config:
      tags:
      - "pipeline:nexus_base"
    columns:
    - name: "Account_Id"
      dataType:
        type: "Bigint"
    - name: "Repay_Type_Code"
      dataType:
        type: "String"
    - name: "From_Date"
      dataType:
        type: "Date"
    - name: "To_Date"
      dataType:
        type: "Date"
    type: "table"
