---
version: 2
models:
- name: "manual_test__repay_type_source_data"
  tags:
  - "prophecy_temp"
- name: "manual_test__repayment_type_extraction"
  tags:
  - "prophecy_temp"
- name: "manual_test__tbk_base"
  tags:
  - "prophecy_temp"
